asean-dev-challenge-21/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{00000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North Hall</fullName>
            </value>
            <value>
                <fullName>South Hall</fullName>
            </value>
            <value>
                <fullName>East Hall</fullName>
            </value>
            <value>
                <fullName>West Hall</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/classes/MainDataManager.cls
public with sharing class MainDataManager {
    
    public static Event__c getEventById(Id eventId){
        try {
            return [SELECT Id, Name FROM Event__c WHERE Id = :eventId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static List<Schedule__c> getSchedulesByEvent(Id eventId){
        try {
            List<Schedule__c> schedsByEventList = [SELECT Id, Name, Area__c, End__c, End_Time__c, Event__c, Start__c, Start_Time__c, Status__c
                                                    FROM Schedule__c
                                                    WHERE Event__c = :eventId];
            return schedsByEventList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static List<Schedule__c> getScheduleByIds(Set<Id> schedIds){
        try {
            return [SELECT Id, Name, Area__c, End__c, End_Time__c, Event__c, Start__c, Start_Time__c, Status__c
                                                    FROM Schedule__c
                                                    WHERE Id IN :schedIds];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static List<Event_Attendee__c> getAttendeesBySchedule(Id schedId){
        try {
            return [SELECT Id, Name, Schedule__c, Contact__c, Contact__r.Name, Contact__r.Phone, Contact__r.Email, Status__c
                                                    FROM Event_Attendee__c
                                                    WHERE Schedule__c = :schedId AND Status__c != 'Cancelled'];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static Event_Attendee__c getAttendeeById(Id attendeeId){
        try {
            return [SELECT Id, Name, Schedule__c, Contact__c, Contact__r.Name, Contact__r.Phone, Contact__r.Email, Status__c
                                                    FROM Event_Attendee__c
                                                    WHERE Id = :attendeeId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static List<Contact> getContactsByName(String searchName){
        String searchNameStr = '%' + searchName + '%';
        try {
            return [SELECT Id, Name, Phone, Email, Account.Name
                FROM Contact
                WHERE Name LIKE :searchNameStr ORDER BY Name ASC];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}