asean-dev-challenge-21/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{00000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>North Hall</fullName>
            </value>
            <value>
                <fullName>South Hall</fullName>
            </value>
            <value>
                <fullName>East Hall</fullName>
            </value>
            <value>
                <fullName>West Hall</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/classes/EventLWCHandler.cls
public with sharing class EventLWCHandler {
    @AuraEnabled (cacheable = true)
    public static List<ScheduleWrapper> getSchedulesByEvent(Id eventId){
        List<Schedule__c> schedulesByEventList = MainDataManager.getSchedulesByEvent(eventId);
        List<ScheduleWrapper> schedulesByEventListWr = new List<ScheduleWrapper>();

        for(Schedule__c sched : schedulesByEventList){
            Boolean disabledStatus = sched.Status__c == 'Complete' || sched.Status__c == 'Cancelled' ? true : false;
            ScheduleWrapper schedWrap = new ScheduleWrapper(sched, disabledStatus);
            schedulesByEventListWr.add(schedWrap);
        }

        return schedulesByEventListWr;
    }

    @AuraEnabled
    public static String updateSingleSchedule(Id schedId, String action){
        Set<Id> schedIds = new Set<Id>{schedId};
        List<Schedule__c> schedRecord = MainDataManager.getScheduleByIds(schedIds);
        String message = '';

        if(schedRecord != null){
            if(action == 'complete'){
                schedRecord[0].Status__c = 'Complete';
                message = schedRecord[0].Name + ' is successfully completed.';
            }else if(action == 'cancel'){
                schedRecord[0].Status__c = 'Cancelled';
                message = schedRecord[0].Name + ' is successfully cancelled.';
            }
            UPDATE schedRecord[0];
        }else{
            message = schedRecord[0].Name + ' failed to be updated.';
        }

        return message;
    }

    @AuraEnabled
    public static String updateBulkSchedule(List<Id> schedIdsList, String action){
        String message = '';
        String status = '';
        Set<Id> schedIds = new Set<Id>();

        if(schedIdsList.size() <> 0){
            if(action == 'complete'){
                status = 'Complete';
                message = 'Event Schedules were successfully completed.';
            }else if(action == 'cancel'){
                status = 'Cancelled';
                message = 'Event Schedules were successfully cancelled.';
            }
            
            for(Id schedId : schedIdsList){
                schedIds.add(schedId);
            }

            List<Schedule__c> schedsList = MainDataManager.getScheduleByIds(schedIds);

            if(schedsList.size() <> 0){
                for(Schedule__c sched : schedsList){
                    sched.Status__c = status;
                }

                UPDATE schedsList;
            }else{
                message = 'Event Schedules failed to be updated.';
            }
        }

        return message;
    }

    @AuraEnabled
    public static String saveNewSchedule(Map<String, Object> schedDetailsMap, Id eventId){
        String message = '';
        Event__c event = MainDataManager.getEventById(eventId);
        List<Schedule__c> newSchedList = new List<Schedule__c>();
        List<Event_Attendee__c> newAttendeeList = new List<Event_Attendee__c>();

        Boolean isRecurring = (Boolean)schedDetailsMap.get('recurring');
        Date startDate = Date.valueOf((String)schedDetailsMap.get('sd'));
        Date endDate = isRecurring ? Date.valueOf((String)schedDetailsMap.get('ed')) : startDate;
        String[] startTimeSplit = String.valueOf(schedDetailsMap.get('st')).split(':');
        Time startTime = Time.newInstance( Integer.valueOf(startTimeSplit[0]), Integer.valueOf(startTimeSplit[1]), 0, 0);
        String[] endTimeSplit = String.valueOf(schedDetailsMap.get('et')).split(':');
        Time endTime = Time.newInstance( Integer.valueOf(endTimeSplit[0]), Integer.valueOf(endTimeSplit[1]), 0, 0);

        if(isRecurring){
            Date st = startDate;

            while(st <= endDate){
                for(Object day : (List<Object>)schedDetailsMap.get('days')){
                    Datetime dt = DateTime.newInstance(st, Time.newInstance(0, 0, 0, 0));
                    String dayOfWeek = dt.format('EEEE');

                    if(String.valueOf(day) == dayOfWeek){
                        Schedule__c newSched = new Schedule__c(
                            Name = event.Name + ' ' + st.format(),
                            Area__c = (String)schedDetailsMap.get('area'),
                            End__c = st,
                            End_Time__c = endTime,
                            Event__c = event.Id,
                            Start__c = st,
                            Start_Time__c = startTime
                        );

                        newSchedList.add(newSched);
                    }
                }
                st = st.addDays(1);
            }
        }else{
            Schedule__c newSched = new Schedule__c(
                Name = event.Name + ' ' + startDate.format(),
                Area__c = (String)schedDetailsMap.get('area'),
                End__c = endDate,
                End_Time__c = endTime,
                Event__c = event.Id,
                Start__c = startDate,
                Start_Time__c = startTime
            );
            newSchedList.add(newSched);
        }

        if(newSchedList.size() > 0){
            INSERT newSchedList;

            for(Schedule__c sched : newSchedList){
                for(Object contactId : (List<Object>)schedDetailsMap.get('contacts')){
                    Event_Attendee__c attendee = new Event_Attendee__c(
                        Contact__c = (Id)contactId,
                        Schedule__c = sched.Id
                    );
                    newAttendeeList.add(attendee);
                }
            }
            if(newAttendeeList.size() > 0){
                INSERT newAttendeeList;
                message = 'New schedule for ' + event.Name + ' was successfully added.';
            }
        }else{
            message = 'New schedule for ' + event.Name + ' failed to be added.';
        }

        return message;
    }

    public class ScheduleWrapper {
        @AuraEnabled
        public Id schedId;
        @AuraEnabled
        public String schedName;
        @AuraEnabled
        public String schedArea;
        @AuraEnabled
        public Date schedStart;
        @AuraEnabled
        public Date schedEnd;
        @AuraEnabled
        public Time schedStartTime;
        @AuraEnabled
        public Time schedEndTime;
        @AuraEnabled
        public Id schedPurpose;
        @AuraEnabled
        public String schedStatus;
        @AuraEnabled
        public Boolean schedIsComplete;  
        @AuraEnabled
        public Boolean schedIsCancelled;
        @AuraEnabled
        public Boolean schedIsSelected;

        public ScheduleWrapper(Schedule__c sched, Boolean disabledStatus){
            schedId = sched.Id;
            schedName = sched.Name;
            schedArea = sched.Area__c;
            schedStart = sched.Start__c;
            schedEnd = sched.End__c;
            schedStartTime = sched.Start_Time__c;
            schedEndTime = sched.End_Time__c;
            schedPurpose = sched.Event__c;
            schedStatus = sched.Status__c;
            schedIsComplete = disabledStatus;  
            schedIsCancelled = disabledStatus;
            schedIsSelected = false;
        }
    }
}