asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{00000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>TextArea</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Event_Attendee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

asean-dev-challenge-21/force-app/main/default/objects/Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

asean-dev-challenge-21/force-app/main/default/classes/ScheduleLWCHandler.cls
public with sharing class ScheduleLWCHandler {
    @AuraEnabled (cacheable = true)
    public static List<Event_Attendee__c> getAttendeesBySchedule(Id schedId){
        return MainDataManager.getAttendeesBySchedule(schedId);
    }

    @AuraEnabled
    public static String cancelAttendee(Id attendeeId, String cancellationReason){
        Event_Attendee__c attendee = MainDataManager.getAttendeeById(attendeeId);
        String message = '';

        if(attendee != null){
            attendee.Status__c = 'Cancelled';
            attendee.Cancellation_Reason__c = cancellationReason;
            message = attendee.Contact__r.Name + ' is successfully cancelled.';
        
            UPDATE attendee;
        }else{
            message = 'Cancellation for ' + attendee.Contact__r.Name + ' failed.'; 
        }

        return message;
    }

    @AuraEnabled (cacheable = true)
    public static List<Contact> getContactsByName(String searchName){
        return MainDataManager.getContactsByName(searchName);
    }

    @AuraEnabled
    public static String saveNewAttendees(List<Id> contactIds, Id schedId){
        String message = '';
        List<Event_Attendee__c> eventAttendees = new List<Event_Attendee__c>();
        System.debug('contactIds');
        System.debug(contactIds);
        if(contactIds.size() <> 0){
            for(Id conId : contactIds){
                Event_Attendee__c attendee = new Event_Attendee__c(
                    Contact__c = conId,
                    Schedule__c = schedId
                );
                eventAttendees.add(attendee);
            }
        
            if(eventAttendees.size() > 0){
                message = 'Attendees are successfully added.';
                INSERT eventAttendees;
            }
                
        }else{
            message = 'Failed to add attendees.';
        }

        return message;
    }
}